include classpath("application.conf")

node-address {
  host = "*"
  port = 9324
}

rest-sqs {
  bind-port = 9324
}

messages-storage {
  enabled = true
  uri = "jdbc:h2:/data/storage"
}

auto-create-queues {
  enabled = false
}
